# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1klfv78h5FdVjQdCF3EsYhDaZZ_fvWIFu
"""

r = float(input("Enter readius of circle: "))
print("Area is: ", 3.14159265359*r*r)

fn = input("enter file name with extension: ")
f = fn.split(".")
print("File extension is: ", f[1])